version: '3.8'
services:
  userbot:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_USERNAME=${BOT_USERNAME}
      - MONGO_URI=${MONGO_URI}
      - SESSION_NAME=${SESSION_NAME}
      - OWNER_ID=${OWNER_ID}